#!/usr/bin/env python

"""The setup script."""

from setuptools import setup, find_packages

with open("README.rst") as readme_file:
    readme = readme_file.read()

with open("HISTORY.rst") as history_file:
    history = history_file.read()

setup(
    extras_require={
        "dev": [
            "alabaster==0.7.12",
            "appdirs==1.4.4",
            "argon2-cffi==20.1.0",
            "async-generator==1.10; python_version >= '3.5'",
            "attrs==20.3.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "babel==2.9.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "backcall==0.2.0",
            "black==19.10b0; python_version >= '3.6'",
            "bleach==3.2.1",
            "bump2version==1.0.1",
            "cached-property==1.5.2",
            "cerberus==1.3.2",
            "certifi==2020.11.8",
            "cffi==1.14.4",
            "chardet==3.0.4",
            "click==7.1.2",
            "colorama==0.4.4; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'",
            "coverage==5.3",
            "cryptography==3.2.1; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'",
            "cycler==0.10.0",
            "decorator==4.4.2",
            "defusedxml==0.6.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'",
            "distlib==0.3.1",
            "docutils==0.16; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'",
            "entrypoints==0.3; python_version >= '2.7'",
            "et-xmlfile==1.0.1",
            "filelock==3.0.12",
            "flake8==3.8.4",
            "guzzle-sphinx-theme==0.7.11",
            "hypothesis==5.41.3",
            "idna==2.10; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "imagesize==1.2.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "iniconfig==1.1.1",
            "ipykernel==5.3.4; python_version >= '3.5'",
            "ipython==7.19.0; python_version >= '3.3'",
            "ipython-genutils==0.2.0",
            "ipywidgets==7.5.1",
            "jdcal==1.4.1",
            "jedi==0.17.2; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'",
            "jeepney==0.6.0; sys_platform == 'linux'",
            "jinja2==2.11.2; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'",
            "json5==0.9.5",
            "jsonschema==3.2.0",
            "jupyter-client==6.1.7; python_version >= '3.5'",
            "jupyter-core==4.7.0; python_version >= '3.6'",
            "jupyter-sphinx==0.3.2",
            "jupyterlab==2.2.9",
            "jupyterlab-pygments==0.1.2",
            "jupyterlab-server==1.2.0; python_version >= '3.5'",
            "keyring==21.5.0; python_version >= '3.6'",
            "kiwisolver==1.3.1; python_version >= '3.6'",
            "markupsafe==1.1.1; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "matplotlib==3.3.3",
            "mccabe==0.6.1",
            "mistune==0.8.4",
            "nbclient==0.5.1; python_version >= '3.6'",
            "nbconvert==6.0.7; python_version >= '3.6'",
            "nbformat==5.0.8; python_version >= '3.5'",
            "nest-asyncio==1.4.3; python_version >= '3.5'",
            "notebook==6.1.5; python_version >= '3.5'",
            "numpy==1.19.4",
            "openpyxl==3.0.5",
            "orderedmultidict==1.0.1",
            "packaging==20.4; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "pandas==1.1.4",
            "pandocfilters==1.4.3",
            "parso==0.7.1; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "pathspec==0.8.1",
            "pathtools==0.1.2",
            "pbr==5.5.1; python_version >= '2.6'",
            "pep517==0.9.1",
            "pexpect==4.8.0; sys_platform != 'win32'",
            "pickleshare==0.7.5",
            "pillow==8.0.1; python_version >= '3.6'",
            "pip-shims==0.5.3; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'",
            "pipenv==2020.11.15; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "pipenv-setup==3.1.1",
            "pipenv-to-requirements==0.9.0",
            "pipfile==0.0.2",
            "pkginfo==1.6.1",
            "plette[validation]==0.2.3; python_version >= '2.6' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "pluggy==0.13.1; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "prometheus-client==0.9.0",
            "prompt-toolkit==3.0.8; python_full_version >= '3.6.1'",
            "ptyprocess==0.6.0; os_name != 'nt'",
            "py==1.9.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "pycodestyle==2.6.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "pycparser==2.20; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "pyflakes==2.2.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "pygments==2.7.2",
            "pyparsing==2.4.7; python_version >= '2.6' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "pyrsistent==0.17.3; python_version >= '3.5'",
            "pytest==6.1.2",
            "pytest-cov==2.10.1",
            "python-dateutil==2.8.1; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "pytz==2020.4",
            "pyyaml==5.3.1",
            "pyzmq==20.0.0; python_version >= '3.5'",
            "readme-renderer==28.0",
            "regex==2020.11.13",
            "requests==2.25.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'",
            "requests-toolbelt==0.9.1",
            "requirementslib==1.5.16; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'",
            "rfc3986==1.4.0",
            "secretstorage==3.3.0; sys_platform == 'linux'",
            "send2trash==1.5.0",
            "six==1.15.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "snowballstemmer==2.0.0",
            "sortedcontainers==2.3.0",
            "sphinx==3.3.1",
            "sphinxcontrib-applehelp==1.0.2; python_version >= '3.5'",
            "sphinxcontrib-devhelp==1.0.2; python_version >= '3.5'",
            "sphinxcontrib-htmlhelp==1.0.3; python_version >= '3.5'",
            "sphinxcontrib-jsmath==1.0.1; python_version >= '3.5'",
            "sphinxcontrib-qthelp==1.0.3; python_version >= '3.5'",
            "sphinxcontrib-serializinghtml==1.1.4; python_version >= '3.5'",
            "terminado==0.9.1; python_version >= '3.6'",
            "testpath==0.4.4",
            "toml==0.10.2; python_version >= '2.6' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "tomlkit==0.7.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'",
            "tornado==6.1; python_version >= '3.5'",
            "tox==3.20.1",
            "tqdm==4.53.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "traitlets==5.0.5; python_version >= '3.7'",
            "travis==0.0.3",
            "twine==3.2.0",
            "typed-ast==1.4.1",
            "urllib3==1.26.2; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4' and python_version < '4'",
            "virtualenv==20.2.1",
            "virtualenv-clone==0.5.4; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "vistir==0.5.2; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "watchdog==0.10.4",
            "wcwidth==0.2.5",
            "webencodings==0.5.1",
            "wheel==0.35.1; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'",
            "widgetsnbextension==3.5.1",
            "xlrd==1.2.0",
            "yamllint==1.25.0",
        ]
    },
    author="Nikolas Ovaskainen",
    author_email="nikolasovaskainen@gmail.com",
    python_requires=">=3.6",
    classifiers=[
        "Development Status :: 2 - Pre-Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
        "Natural Language :: English",
        "Programming Language :: Python :: 3.8",
    ],
    description="Drillcore Transformations allows for alpha, beta and gamma drillcore transformations.",
    entry_points={
        "console_scripts": ["drillcoretransform=drillcore_transformations.cli:cli",],
    },
    install_requires=[
        "click==7.1.2",
        "cycler==0.10.0",
        "et-xmlfile==1.0.1",
        "jdcal==1.4.1",
        "kiwisolver==1.3.1; python_version >= '3.6'",
        "matplotlib==3.3.3",
        "numpy==1.19.4",
        "openpyxl==3.0.5",
        "pandas==1.1.4",
        "pillow==8.0.1; python_version >= '3.6'",
        "pyparsing==2.4.7; python_version >= '2.6' and python_version not in '3.0, 3.1, 3.2, 3.3'",
        "python-dateutil==2.8.1; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
        "pytz==2020.4",
        "six==1.15.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
        "xlrd==1.2.0",
    ],
    license="GNU General Public License v3",
    long_description=readme + "\n\n" + history,
    include_package_data=True,
    keywords="drillcore_transformations",
    name="drillcore_transformations",
    packages=find_packages(
        include=["drillcore_transformations", "drillcore_transformations.*"]
    ),
    setup_requires=[],
    test_suite="tests",
    tests_require=[],
    url="https://github.com/nialov/drillcore-transformations",
    version="0.2.5",
    zip_safe=False,
)
