jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: DeterminateSystems/nix-installer-action@v19
    - uses: cachix/cachix-action@v16
      with:
        name: nialov
    - name: Check flake
      run: nix -Lv flake check
    timeout-minutes: 60
'on':
  pull_request: {}
  push: {}
  workflow_dispatch: {}
